### ISSUE TITLE
prepare_data.py - "IndexError: tuple index out of range" error

### ISSUE THREAD

**Issue by armor99** [ucbdrive/scalabel#142]
I ran the following command to prepare images from mp4 10 minute mp4 video:
`user-vid3:~/annotation$ python3 ../projects/scalabel/scripts/prepare_data.py -i out001.mp4 -t images -f 1
processing 1 video(s) ...
[RUNNING] ffmpeg -i out001.mp4 -r 1 -qscale:v 2 images/out001-%07d.jpg
Traceback (most recent call last):
  File "../projects/scalabel/scripts/prepare_data.py", line 141, in <module>
    main()
  File "../projects/scalabel/scripts/prepare_data.py", line 133, in main
    output = prepare_data(args)
  File "../projects/scalabel/scripts/prepare_data.py", line 85, in prepare_data
    for img in file_list]
  File "../projects/scalabel/scripts/prepare_data.py", line 85, in <listcomp>
    for img in file_list]
IndexError: tuple index out of range
`
It does output the sequence of images from ffmpeg, but seems to fail after that.

**Comment by kevinsu628** [comment]
I had this error a few days ago. 
I eventually changed line 84 in prepare_data.py to this:

'videoName':  '{}'.format(*img.split('/')[-1].split('-')[:-1])

Hope it helps!

**Comment by fyu** [comment]
This should be fixed by #170
